#!/usr/bin/python3
from sys import argv
import time
from math import sqrt

numbers = []


def main():

    if len(argv) != 2:
        print("Usage: factors <file>")
        exit()

    try:
        with open(argv[1], 'r', encoding="utf-8") as file:
            for line in file:
                numbers.append(int(line.replace('\n', '')))

    except FileNotFoundError:
        print("File not found")
        exit()

    start = time.time()

    for number in numbers:
        denominator = 2
        limit = round(sqrt(number))
        first_number, second_number = factor(number, denominator, limit)
        if first_number and second_number:
            print("{}={}*{}".format(number, first_number, second_number))

    if time.time() - start > 5:
        print("Time out")
        exit()


def factor(number, denominator, limit):
    while (denominator <= limit):
        if number % denominator == 0:
            return (int(number / denominator), int(denominator))
        denominator += 1
    return (None, None)


if __name__ == '__main__':
    main()
